export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
//Login Actions
export const SHOW_LOADING_LOGIN = 'SHOW_LOADING_LOGIN'
export const HIDE_LOADING_LOGIN = 'HIDE_LOADING_LOGIN'
export const SHOW_LOGIN_ERROR_MESSAGE = 'SHOW_LOGIN_ERROR_MESSAGE'
export const HIDE_LOGIN_ERROR_MESSAGE = 'SHOW_LOGIN_ERROR_MESSAGE'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
