//Login Actions
export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
export const SHOW_LOADING_LOGIN = 'SHOW_LOADING_LOGIN'
export const HIDE_LOADING_LOGIN = 'HIDE_LOADING_LOGIN'
export const SHOW_LOGIN_ERROR_MESSAGE = 'SHOW_LOGIN_ERROR_MESSAGE'
export const HIDE_LOGIN_ERROR_MESSAGE = 'SHOW_LOGIN_ERROR_MESSAGE'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const RETRIEVE_ACCOUNTS = 'RETRIEVE_ACCOUNTS'
export const RETRIEVE_WATCH_LIST = 'RETRIEVE_WATCH_LIST'

//Search Actions
export const RETRIEVE_SYMBOLS_LIST = 'RETRIEVE_SYMBOLS_LIST'
export const LOGOUT = 'LOGOUT'

//Symbol View
export const RETRIEVE_CHART_DATA = 'RETRIEVE_CHART_DATA'
export const RETRIEVE_NEWS = 'RETRIEVE_NEWS'
export const CLEAN_NEWS = 'CLEAN_NEWS'
